# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Assert variables are defined
  ansible.builtin.assert:
    that:
    - workspace is defined
    - blueprint_yaml is defined
    - custom_vars.modules_to_remove is defined

- name: Remove modules
  ansible.builtin.command: "{{ workspace }}/tools/cloud-build/daily-tests/remove_module.py --blueprint {{ blueprint_yaml }} --module {{ module_to_remove }}"
  loop: "{{ custom_vars.modules_to_remove }}"
  loop_control:
    loop_var: module_to_remove
