# Copyright 2026 "Google LLC"
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dummy-device-plugin
  namespace: kube-system
  labels:
    app: dummy-device-plugin
spec:
  selector:
    matchLabels:
      app: dummy-device-plugin
  template:
    metadata:
      labels:
        app: dummy-device-plugin
    spec:
      hostNetwork: true
      containers:
      - name: generic-device-plugin
        image: us-central1-docker.pkg.dev/hpc-toolkit-dev/hpc-toolkit-repo/generic-device-plugin:0.2.0
        args:
        - --domain=test-locks
        - '--device={"name": "slurm", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "ml-slurm", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "slurm-gcp-v6-rocky8", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "slurm-gcp-v6-ubuntu", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "slurm-gcp-v6-debian", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "slurm-gcp-v6-reconfig-size", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "slurm-gcp-v6-ssd", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "hpc-build-slurm-image", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "hpc-enterprise-slurm", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "hcls", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "a2-highgpu", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "gke-a2-highgpu-kueue-onspot", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "a3-ultragpu", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "a3-highgpu", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "a3-megagpu", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "gke-a3-megagpu-onspot", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "ml-a3-highgpu-onspot-slurm", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "gke-a3-ultragpu-onspot", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "gke-a3-highgpu-onspot", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "ml-a3-ultragpu-onspot-slurm", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "ml-a3-ultragpu-onspot-jbvms", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "a4-highgpu", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "gke-a4-onspot", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "a4x", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "gke-a4x", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "ml-a4-highgpu-onspot-slurm", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "ml-gke-e2e", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "ml-gke", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "g4-standard", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "gke-g4-confidential", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "ml-g4-onspot-slurm", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "ml-a4x-highgpu-slurm", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "ml-a3-megagpu-onspot-slurm", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "tpu-v6e", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "gke-tpu-v6e", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "tpu-v5e", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "gke-tpu-v5e", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "tpu-v5p", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "gke-tpu-v5p", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "tpu7x-standard", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "gke-tpu-7x", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "gke-g4-onspot", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "h4d", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "h4d-vm", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "z4m", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "z4m-vm", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "gke-h4d-onspot", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "ml-h4d-onspot-slurm", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "ansible-vm", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "batch-mpi", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "batch", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "crd-ubuntu", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "netapp-volumes", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "crd", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "e2e", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "gke-inactive-reservation", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "gke-managed-hyperdisk", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "gke-storage", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "vm-storage", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "slurm-storage", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "slurm-rapid-storage", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "gke", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "htc-slurm", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "htcondor", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "monitoring", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "packer", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "pfs-managed-lustre-slurm", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "pfs-managed-lustre-vm", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "slurm-flex", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "slurm-gcp-v6-simple-job", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "slurm-gcp-v6-startup-scripts", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "slurm-gcp-v6-topology", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "slurm-gke", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "spack-gromacs", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "gcluster-dockerfile", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - '--device={"name": "gke-managed-lustre", "groups": [{"count": 1000, "paths": [{"path": "/dev/null"}]}]}'
        - --listen=:8085
        securityContext:
          privileged: true
        volumeMounts:
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
        - name: dev
          mountPath: /dev
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: dev
        hostPath:
          path: /dev
