# Copyright 2026 "Google LLC"
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: batch/v1
kind: Job
metadata:
  name: nccl-test
  labels:
    app: nccl-test
spec:
  ttlSecondsAfterFinished: 1200
  suspend: False
  template:
    metadata:
      labels:
        app: nccl-test
    spec:
      restartPolicy: OnFailure
      nodeSelector:
        cloud.google.com/gke-nodepool: g4-standard-96-g4-pool # Replace with your specific nodepool name if different.
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: nccl-test
        image: nvidia/cuda:12.2.0-devel-ubuntu22.04
        resources:
          limits:
            nvidia.com/gpu: 2  # Update this to match the number of GPUs per node in your cluster
          requests:
            nvidia.com/gpu: 2  # Update this to match the number of GPUs per node in your cluster
        env:
        - name: NCCL_DEBUG
          value: "INFO"
        - name: NCCL_P2P_LEVEL
          value: "PHB"  # Update this to "SYS" if using 8-GPU g4-standard-384 machines.
        command:
        - /bin/bash
        - -c
        - |
          set -ex

          # Install dependencies
          apt-get update && \
          apt-get install -y git build-essential libopenmpi-dev openmpi-bin libnccl2 libnccl-dev

          # Clone and build NCCL tests
          git clone https://github.com/NVIDIA/nccl-tests.git
          cd nccl-tests
          make MPI=1 MPI_HOME=/usr/lib/x86_64-linux-gnu/openmpi

          # Run all_reduce_perf
          # Adjust -g (num gpus) as needed.
          mpirun \
            -np 1 \
            --allow-run-as-root \
            -x NCCL_DEBUG -x NCCL_P2P_LEVEL \
            /nccl-tests/build/all_reduce_perf \
            -b 1M -e 8G -f 2 -g 2 -w 5 --iters 100
        volumeMounts:
        - name: shared-memory
          mountPath: /dev/shm
      volumes:
      - name: shared-memory
        emptyDir:
          medium: Memory
          sizeLimit: 2Gi
