# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

blueprint_name: spack-buildcache

vars:
  project_id:  ## Set GCP Project ID Here ##
  deployment_name: spack-buildcache
  region: us-central1
  zone: us-central1-c

deployment_groups:
- group: primary
  modules:
  - id: network1
    source: modules/network/pre-existing-vpc

  - id: spack-setup
    source: ./community/modules/scripts/spack-setup
    settings:
      install_dir: /apps/spack
      spack_url: https://github.com/spack/spack
      spack_ref: v0.17.1

  - id: spack-execute
    source: community/modules/scripts/spack-execute
    use: [spack-setup]
    settings:
      log_file: /var/log/spack.log
      data_files:
      - destination: /apps/spack/env_file.yaml
        content: |
          spack:
            definitions:
            - compilers:
              - gcc@10.3.0
            - mpis:
              - intel-mpi@2018.4.274
            - mpi_packages:
              - gromacs@2021.2
            specs:
            - matrix:
              - - $mpis
              - - $%compilers
            - matrix:
              - - $mpi_packages
              - - $%compilers
              - - $^mpis
      - destination: /apps/spack/mixed_env_file.yaml
        content: |
          spack:
            specs:
              intel-mpi@20184.274 %gcc@10.3.0
      commands: |
        spack config --scope site add config:install_tree:padded_length:128

        spack gpg init
        spack gpg create "Robert Pirsig" pirsig@zamm.org

        spack install gcc@10.3.0 target=x86_64
        spack load gcc@10.3.0 target=x86_64
        spack compiler find --scope site

        if ! spack env list | grep -q test-file; then
          spack env create test-file /apps/spack/env_file.yaml
          spack env activate test-file
          spack concretize
          spack install
        fi

        if ! spack env list | grep -q test-package; then
          spack env create test-package
        fi
        spack env activate test-package
        spack add intel-mpi@2018.4.274 %gcc@10.3.0
        spack add gromacs@2021.2 %gcc@10.3.0 ^intel-mpi@2018.4.274
        spack concretize
        spack install

        if ! spack env list | grep -q test-mixed; then
          spack env create test-mixed /apps/spack/mixed_env_file.yaml
        fi
        spack env activate test-mixed
        spack add gromacs@2021.2 %gcc@10.3.0 ^intel-mpi@2018.4.274
        spack concretize
        spack install

        MIRROR_URL=gs://<name of your bucket>
        spack buildcache create --mirror-url $MIRROR_URL -af \$(spack find --format /{hash});
        spack gpg publish --mirror-url $MIRROR_URL;
        spack buildcache update-index --mirror-url $MIRROR_URL --keys;

  - id: spack-startup
    source: modules/scripts/startup-script
    settings:
      runners:
      - type: data
        source: /local/path/to/spack/key.gpg
        destination: /tmp/spack_key.gpg
      - type: shell
        content: |
          #!/bin/bash
          mkdir /apps
          chmod a+rwx /apps
        destination: apps_create.sh
      - $(spack-execute.spack_runner)
      - type: shell
        destination: shutdown.sh
        content: shutdown -h

  - id: spack-build
    source: modules/compute/vm-instance
    use:
    - network1
    - spack-startup
    settings:
      name_prefix: spack-builder
      machine_type: n2-standard-8
      service_account_scopes:
      - "https://www.googleapis.com/auth/devstorage.read_write"
      - "https://www.googleapis.com/auth/logging.write"
      - "https://www.googleapis.com/auth/monitoring.write"
      - "https://www.googleapis.com/auth/servicecontrol"
      - "https://www.googleapis.com/auth/service.management.readonly"
      - "https://www.googleapis.com/auth/trace.append"
