# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Assert variables are defined
  ansible.builtin.assert:
    that:
    - region is defined
    - custom_vars.project is defined

- name: Get cluster credentials for kubectl
  delegate_to: localhost
  ansible.builtin.shell: |
    gcloud container clusters get-credentials {{ deployment_name }} --region {{ region }} --project {{ custom_vars.project }} --verbosity=debug

- name: Get GKE cluster version
  delegate_to: localhost
  ansible.builtin.shell: |
    gcloud container clusters describe {{ deployment_name }} --region {{ region }} --project {{ custom_vars.project }} --format="value(currentMasterVersion)"
  register: gke_version_info

- name: Print GKE cluster version
  ansible.builtin.debug:
    msg: "GKE Cluster Version: {{ gke_version_info.stdout }}"

- name: Verify TCPX and NRI DaemonSets are fully deployed
  delegate_to: localhost
  ansible.builtin.shell: |
    echo "Waiting for nccl-tcpx-installer daemonset..."
    kubectl rollout status daemonset nccl-tcpx-installer -n kube-system --timeout=1200s
    echo "Waiting for device-injector daemonset..."
    kubectl rollout status daemonset device-injector -n kube-system --timeout=1200s
    kubectl get daemonsets -n kube-system nccl-tcpx-installer device-injector
  register: daemonset_status

- name: Print DaemonSet status
  ansible.builtin.debug:
    msg: "{{ daemonset_status.stdout }}"

- name: Verify Kueue Queues are ready
  delegate_to: localhost
  ansible.builtin.shell: |
    echo "Checking ClusterQueues and LocalQueues..."
    kubectl get clusterqueue
    kubectl get localqueue
  register: kueue_status

- name: Print Kueue Queues status
  ansible.builtin.debug:
    msg: "{{ kueue_status.stdout }}"

- name: Deploy NCCL test Pods
  delegate_to: localhost
  ansible.builtin.shell: |
    kubectl apply -f {{ workspace }}/examples/gke-a3-highgpu/nccl-test.yaml -v=9

- name: Wait for NCCL test Pods to be ready
  delegate_to: localhost
  ansible.builtin.shell: |
    kubectl wait --for=condition=Ready pod/nccl-test-host-1 pod/nccl-test-host-2 --timeout=1200s

- name: Run allgather benchmark on host 1 and fetch logs
  delegate_to: localhost
  ansible.builtin.shell: |
    kubectl exec nccl-test-host-1 -c nccl-test -- /bin/bash -c "cp /configs/allgather.sh /scripts/allgather.sh"
    kubectl exec nccl-test-host-1 -c nccl-test -- /scripts/allgather.sh nccl-host-1 nccl-host-2 > pod_logs.txt
    cat pod_logs.txt
  register: nccl_test_logs

- name: Print the NCCL test logs
  debug:
    msg: "{{ nccl_test_logs.stdout }}"

- name: Ensure average bus bandwidth is >= 25 GB/s
  delegate_to: localhost
  ansible.builtin.shell: |
    grep -o '# Avg bus bandwidth    : [0-9\.]*' pod_logs.txt | cut -d ':' -f 2 | awk '{$1=$1;print}'
  register: avg_bus_bandwidth
  failed_when: avg_bus_bandwidth.stdout | float < 25

- name: Clean up
  delegate_to: localhost
  ansible.builtin.shell: |
    kubectl delete -f {{ workspace }}/examples/gke-a3-highgpu/nccl-test.yaml
