# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Assert variables are defined
  ansible.builtin.assert:
    that:
    - custom_vars.mounts is defined

- name: Get mount info
  ansible.builtin.stat:
    path: "{{ item }}"
  register: stat_mounts
  loop: "{{ custom_vars.mounts }}"
- name: Check if mount exists
  ansible.builtin.fail:
    msg: "{{ item.item }} not mounted"
  when: not item.stat.exists
  loop: "{{ stat_mounts.results }}"
