# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# The instructions for installing HTCondor may change with time, although we
# anticipate that they will stay fixed for the 10.x releases. Find up-to-date
# recommendations at:
## https://htcondor.readthedocs.io/en/latest/getting-htcondor/from-our-repositories.html

---
- name: Ensure HTCondor is installed
  hosts: all
  vars:
    enable_docker: true
  become: true
  module_defaults:
    ansible.builtin.yum:
      lock_timeout: 300
  tasks:
  - name: Enable EPEL repository
    ansible.builtin.yum:
      name:
      - epel-release
  - name: Enable HTCondor Feature Release repository
    ansible.builtin.yum_repository:
      name: htcondor-feature
      description: HTCondor Feature Releases (10.x.0)
      file: htcondor
      baseurl: https://research.cs.wisc.edu/htcondor/repo/10.x/el$releasever/$basearch/release
      gpgkey: https://research.cs.wisc.edu/htcondor/repo/keys/HTCondor-10.x-Key
      gpgcheck: true
      repo_gpgcheck: true
      priority: "90"
  - name: Enable HTCondor Feature Release Updates repository
    ansible.builtin.yum_repository:
      name: htcondor-feature-update
      description: HTCondor Feature Release Updates (10.x.y)
      file: htcondor
      baseurl: https://research.cs.wisc.edu/htcondor/repo/10.x/el$releasever/$basearch/update
      gpgkey: https://research.cs.wisc.edu/htcondor/repo/keys/HTCondor-10.x-Key
      gpgcheck: true
      repo_gpgcheck: true
      priority: "90"
  - name: Install HTCondor
    ansible.builtin.yum:
      name: condor-{{ condor_version | default("10.*") | string }}
      state: present
  - name: Ensure token directory
    ansible.builtin.file:
      path: /etc/condor/tokens.d
      mode: 0700
      owner: root
      group: root
  - name: Install Docker and configure HTCondor to use it
    when: enable_docker | bool  # allows string to be passed at CLI
    block:
    - name: Setup Docker repo
      ansible.builtin.yum_repository:
        name: docker-ce-stable
        description: Docker CE Stable - $basearch
        baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
        enabled: yes
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg
    - name: Install Docker
      ansible.builtin.yum:
        name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
    - name: Enable Docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true
    - name: Add condor to docker group
      ansible.builtin.user:
        name: condor
        groups: docker
        append: yes
