# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

blueprint_name: merge_flatten

vars:
  project_id:  #
  deployment_name: merge_flatten
  region: us-east4
  zone: us-east4-c

deployment_groups:
- group: zero
  modules:
  - id: network
    source: modules/network/vpc

  - id: first-fs
    source: modules/file-system/filestore
    use: [network]
    settings:
      local_mount: /first

  - id: second-fs
    source: modules/file-system/filestore
    use: [network]
    settings:
      local_mount: /first
  
  - id: first-vm
    source: modules/compute/vm-instance
    use: [first-fs]
    settings:
      labels: {"green": "sleeves"}
    
  - id: second-vm
    source: modules/compute/vm-instance
    use: [first-fs, second-fs]
