blueprint_name: slice_controller_test

vars:
  project_id: invalid-project
  deployment_name: slice-controller-test
  region: us-east4

deployment_groups:
- group: one
  modules:
  - id: network
    source: modules/network/vpc
  - id: cluster
    source: modules/scheduler/gke-cluster
    use: [network]
    settings:
      enable_slice_controller: true