# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Compute default secret_name if none provided
  set_fact:
    secret_name: "vdi-user-password-{{ item.username }}-{{ deployment_name }}"
  when:
    - item.password is not defined
    - item.secret_name is not defined

- name: Determine password source for user {{ item.username }}
  ansible.builtin.set_fact:
    password_source: >-
      {%- if item.secret_name is defined -%}secret
      {%- elif item.password is defined -%}password
      {%- else -%}generate{%- endif -%}

- name: Fetch existing Secret Manager password for user {{ item.username }}
  ansible.builtin.uri:
    url: "https://secretmanager.googleapis.com/v1/projects/{{ item.secret_project | default(project_id) }}/secrets/{{ item.secret_name }}/versions/latest:access"
    method: GET
    headers:
      Authorization: "Bearer {{ access_token_result.json.access_token }}"
      Content-Type: "application/json"
    return_content: true
  register: sm_result
  failed_when: false
  when: password_source | trim == "secret"

- name: Set VDI user password from Secret Manager
  ansible.builtin.set_fact:
    vdiuser_password: "{{ sm_result.json.payload.data | b64decode }}"
  when: password_source == "secret" and sm_result.status == 200

- name: Generate random password for user {{ item.username }}
  ansible.builtin.set_fact:
    vdiuser_password: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters,digits') }}"
  when: password_source == "generate"

- name: Set user password from provided value
  ansible.builtin.set_fact:
    vdiuser_password: "{{ item.password }}"
  when: password_source == "password"

- name: Create secret for user {{ item.username }} (provided password)
  ansible.builtin.uri:
    url: "https://secretmanager.googleapis.com/v1/projects/{{ item.secret_project | default(project_id) }}/secrets?secretId=vdi-user-password-{{ item.username }}-{{ deployment_name }}"
    method: POST
    headers:
      Authorization: "Bearer {{ access_token_result.json.access_token }}"
      Content-Type: "application/json"
    body_format: json
    body:
      replication:
        automatic: {}
    status_code: [200, 409]  # 409 = already exists
  when: password_source == "password"

- name: Store provided password in Secret Manager for user {{ item.username }}
  ansible.builtin.uri:
    url: "https://secretmanager.googleapis.com/v1/projects/{{ item.secret_project | default(project_id) }}/secrets/vdi-user-password-{{ item.username }}-{{ deployment_name }}:addVersion"
    method: POST
    headers:
      Authorization: "Bearer {{ access_token_result.json.access_token }}"
      Content-Type: "application/json"
    body_format: json
    body:
      payload:
        data: "{{ item.password | b64encode }}"
  when: password_source == "password"

- name: Create secret for user {{ item.username }}
  ansible.builtin.uri:
    url: "https://secretmanager.googleapis.com/v1/projects/{{ item.secret_project | default(project_id) }}/secrets?secretId={{ item.secret_name | default(secret_name) }}"
    method: POST
    headers:
      Authorization: "Bearer {{ access_token_result.json.access_token }}"
      Content-Type: "application/json"
    body_format: json
    body:
      replication:
        automatic: {}
    status_code: [200, 409]  # 409 = already exists
  when: password_source == "generate"

- name: Store generated password in Secret Manager for user {{ item.username }}
  ansible.builtin.uri:
    url: "https://secretmanager.googleapis.com/v1/projects/{{ item.secret_project | default(project_id) }}/secrets/{{ item.secret_name | default(secret_name) }}:addVersion"
    method: POST
    headers:
      Authorization: "Bearer {{ access_token_result.json.access_token }}"
      Content-Type: "application/json"
    body_format: json
    body:
      payload:
        data: "{{ vdiuser_password | b64encode }}"
  when: password_source == "generate"

- name: Build enriched user list
  ansible.builtin.set_fact:
    vdi_users_updated: >-
      {{
        (vdi_users_updated | default([]))
        + [
          item
          | combine({ 'password': vdiuser_password })
          | combine(
              (vnc_flavor | lower in ['tightvnc', 'tigervnc']) 
              | ternary({ 
                  'vncserver_password': lookup('community.general.random_string', length=8, special=false),
                  'display_number': item.port | int - 5900
                }, {})
            )
        ]
      }}
