/**
 * Copyright 2022 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

output "instructions" {
  description = "Installation instructions for the hybrid configurations created by this module."
  value       = <<-EOD
      To install the configurations generated by this module, follow these
      steps:

      1. Add the following line to your `slurm.conf` file:
      `include <<OUTPUT_DIR>>/cloud.conf`

      2. Add the following line to your `gres.conf` file:
      `include <<OUTPUT_DIR>>/cloud_gres.conf`

      3. Ensure your output directory is owned by the slurm user:
      `sudo chown slurm <<OUTPUT_DIR>>`

      3. With the slurm user on the controller, add a cronjob/crontab to run
      slurmsync.py regularly:
      `*/1 * * * * <<OUTPUT_DIR>>/slurmsync.py`

      4. Restart the slurmctld service on the controller:
      `sudo systemctl restart slurmctld`

      5. Restart the slurmd service on the compute nodes:
      `sudo systemctl restart slurmd`

      NOTE: Your on-premise configuration may vary and require additional
      configuration steps. For more information, see the
      SchedMD/slurm-gcp hybrid documentation:
      https://github.com/SchedMD/slurm-gcp/blob/master/docs/hybrid.md#manual-configurations
      EOD
}
