output "instructions" {
  description = "Installation instructions for the hybrid configurations created by this module."
  value       = <<-EOD
      To install the configurations generated by this module, follow these
      steps:

      1. Add the following line to your `slurm.conf` file:
      `include <<OUTPUT_DIR>>/cloud.conf`

      2. Add the following line to your `gres.conf` file:
      `include <<OUTPUT_DIR>>/cloud_gres.conf`

      3. With the slurm user on the controller, add a cronjob/crontab to run
      slurmsync.py regularly:
      `*/1 * * * * <<OUTPUT_DIR>>/slurmsync.py`

      4. Restart the slurmctld service on the controller:
      `sudo systemctl restart slurmctld`

      5. Restart the slurmd service on the compute nodes:
      `sudo systemctl restart slurmd`

      NOTE: Your on-premise configuration may vary and require additional
      configuration steps. For more information, see the
      SchedMD/slurm-gcp hybrid documentation:
      https://github.com/SchedMD/slurm-gcp/blob/master/docs/hybrid.md#manual-configurations
      EOD
}