# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

terraform_backend_defaults:
  type: gcs
  configuration:
    bucket: # supply existing bucket to store Terraform state

vars:
  deployment_name: # supply unique deployment name
  project_id: # supply existing project id
  region:  # supply region with a4x-highgpu-4g capacity in reservation
  zone: # supply zone with a4x-highgpu-4g capacity in reservation
  a4x_cluster_size:  # supply a4x-highgpu-4g reservation size
  #Provisioning model, select one (only one selection is valid), lack of selection will rely on on-demand capacity
  a4x_dws_flex_enabled: false
  a4x_enable_spot_vm: false
  a4x_reservation_name: # supply a4x-highgpu-4g reservation name
  accelerator_topology: # supply accelerator topology
  a4x_dws_flex_max_run_duration: 7 # Maximum number of days for which DWS Flex is needed, cannot exceed 7
