# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM golang:bullseye

RUN apt-get -y update && apt-get install -y python3-pip git shellcheck && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install pre-commit && rm -rf ~/.cache/pip/*

RUN go install github.com/terraform-docs/terraform-docs@latest      && \
    go install golang.org/x/lint/golint@latest                      && \
    go install github.com/fzipp/gocyclo/cmd/gocyclo@latest          && \
    go install github.com/go-critic/go-critic/cmd/gocritic@latest   && \
    go install github.com/google/addlicense@latest                  && \
    go install mvdan.cc/sh/v3/cmd/shfmt@latest                      && \
    go install golang.org/x/tools/cmd/goimports@latest              && \
    go install honnef.co/go/tools/cmd/staticcheck@latest
