/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by update-dependencies.sh. DO NOT EDIT.
package dependencies

var (
        TerraformVersion = "1.12.2"
        PackerVersion    = "1.15.4"

        ExpectedChecksums = map[string]string{
                "terraform_darwin_amd64":  "c65aa74bed1dbb1c48ba4bbab11f08e7f7eeb54a422146561490275340468f19",
                "terraform_darwin_arm64":  "1ca02f336ff4f993d6441806d38a0bcc0bbca0e3c877b84c9c2dc80cfcd0dc8b",
                "terraform_freebsd_386":   "1775139ffda321f730f91c0ce2bb2364c8eafe32c0d3950788086302d49d3005",
                "terraform_freebsd_amd64": "4a72a9770e971ad0fead17221b9488f4552d1a58a860b2a6b2c66ca15376b40e",
                "terraform_freebsd_arm":   "3ec3d8028b4e2977853cbf8f3119e2bbebb14c5bfa3542d90f0d32cac1b0df7d",
                "terraform_linux_386":     "73b380f262324985e911323ecc446066343ffe78add6570a122b7444b04b120b",
                "terraform_linux_amd64":   "1eaed12ca41fcfe094da3d76a7e9aa0639ad3409c43be0103ee9f5a1ff4b7437",
                "terraform_linux_arm":     "4d5d39d57755a45b7bb6c6ad7301ac3c301eba44b647e2d0ca79c117cb817259",
                "terraform_linux_arm64":   "f8a0347dc5e68e6d60a9fa2db361762e7943ed084a773f28a981d988ceb6fdc9",
                "terraform_openbsd_386":   "f92bbb5c7f2141d5b28a69d16770fd8b6afff5ff1b8ab0cfaab32e833b793b41",
                "terraform_openbsd_amd64": "7dc9bbfcf814386f3d680dc86d5f99eca78d2560863c0be219f9627c863ee903",
                "terraform_solaris_amd64": "2df462be97b21c61be3e82156f0d0f929808c2b9a9e2a1ce537bafcbbff61b80",
                "terraform_windows_386":   "5503656530278ff63741fd74609e847e181969ee96dd76fb722e11da40e19063",
                "terraform_windows_amd64": "0a1565ace9da37c2778868c2e97452d8fc25e40e530bafbbab97231e69b0a201",
                "packer_darwin_amd64":     "b3be60b44dcb74e7962afe22cc10b89a09c74b626fcd52f49ecee32b07b99e71",
                "packer_darwin_arm64":     "d95ba177dd2ebb84d7d155493b4188ec2a519d2c3b041528db5b63a6aff9da80",
                "packer_freebsd_386":      "8e9e68f92ac4eddd0dbe3f80d5f2e8d22f6b5ae31dacd7b2e43d64a51dbf5ebb",
                "packer_freebsd_amd64":    "6baf41dea675dd694f89e11853b13c15099269129e603df8495063dcaeba6cc4",
                "packer_freebsd_arm":      "d28c3c689ac73b96c0a5d423393d0fb8d26eff28e34281d2ecdf174ca36b4d0a",
                "packer_linux_386":        "65ae4f04bb4ec5da807920030de3ea8a5e78a14c65ee37c00ba30c9fb22f961f",
                "packer_linux_amd64":      "15f97a6a99645c7d5308c609973b5280837b38e112beac413ccbce80da927cf1",
                "packer_linux_arm":        "b4830f7963fc34de7281e1d3a6e5dbb1d492334237f9247ec8dd2b13c552a409",
                "packer_linux_arm64":      "23e6d2e596dd9e2527e0f7bea9aedd26059729375a0d17c462c2621f1b97b82d",
                "packer_linux_ppc64le":    "e0a2b050ff5756272815b745e4f1ff74453a2844b676bf5e5c151225d1f0c489",
                "packer_netbsd_386":       "628fd6278571c4832a2ce81bace79760802370eb1554d254149f0736af9c181c",
                "packer_netbsd_amd64":     "dea65ae25cf3877841c8c330181226e8187912082d7e55363e283120deb3afb4",
                "packer_netbsd_arm":       "f4a1e6b54a5097f9c5adc2a09bf417086da95c0c14b2e7c02f487911f487d4b8",
                "packer_openbsd_386":      "2c539092b4b4ad026cb588b515c619bcfb85f17a90ca2e74e0267aa8bb4804b9",
                "packer_openbsd_amd64":    "bd402f28acc99796debcaa1055081945a31a378c44c710fe01d061fa01c91cf0",
                "packer_openbsd_arm":      "cddc069d5b2c2c3133ba55a31482113560a06cbbdcdc92489024fbcd5e2dcc19",
                "packer_solaris_amd64":    "9ad4f0653b0569c24c73f39acd8b8d7655377fce67434ee9fe2e268bdc9b6895",
                "packer_windows_386":      "661b634045beb794435eaa60a09cb90f15fa4ff860ebbf68bc6648f61dc169f6",
                "packer_windows_amd64":    "a50db29fae2972f5e5d05ecee23f80e303d605f8132dc2167848fc89184f044b",
        }
)
