/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by update-dependencies.sh. DO NOT EDIT.
package dependencies

var (
	TerraformVersion = "1.12.2"
	PackerVersion    = "1.15.0"

	ExpectedChecksums = map[string]string{
		"terraform_darwin_amd64":  "c65aa74bed1dbb1c48ba4bbab11f08e7f7eeb54a422146561490275340468f19",
		"terraform_darwin_arm64":  "1ca02f336ff4f993d6441806d38a0bcc0bbca0e3c877b84c9c2dc80cfcd0dc8b",
		"terraform_freebsd_386":   "1775139ffda321f730f91c0ce2bb2364c8eafe32c0d3950788086302d49d3005",
		"terraform_freebsd_amd64": "4a72a9770e971ad0fead17221b9488f4552d1a58a860b2a6b2c66ca15376b40e",
		"terraform_freebsd_arm":   "3ec3d8028b4e2977853cbf8f3119e2bbebb14c5bfa3542d90f0d32cac1b0df7d",
		"terraform_linux_386":     "73b380f262324985e911323ecc446066343ffe78add6570a122b7444b04b120b",
		"terraform_linux_amd64":   "1eaed12ca41fcfe094da3d76a7e9aa0639ad3409c43be0103ee9f5a1ff4b7437",
		"terraform_linux_arm":     "4d5d39d57755a45b7bb6c6ad7301ac3c301eba44b647e2d0ca79c117cb817259",
		"terraform_linux_arm64":   "f8a0347dc5e68e6d60a9fa2db361762e7943ed084a773f28a981d988ceb6fdc9",
		"terraform_openbsd_386":   "f92bbb5c7f2141d5b28a69d16770fd8b6afff5ff1b8ab0cfaab32e833b793b41",
		"terraform_openbsd_amd64": "7dc9bbfcf814386f3d680dc86d5f99eca78d2560863c0be219f9627c863ee903",
		"terraform_solaris_amd64": "2df462be97b21c61be3e82156f0d0f929808c2b9a9e2a1ce537bafcbbff61b80",
		"terraform_windows_386":   "5503656530278ff63741fd74609e847e181969ee96dd76fb722e11da40e19063",
		"terraform_windows_amd64": "0a1565ace9da37c2778868c2e97452d8fc25e40e530bafbbab97231e69b0a201",
		"packer_darwin_amd64":     "a565b825aed17ac9a7c422b5ed22e6598dd42b9f705de161695853b1f5c6bd80",
		"packer_darwin_arm64":     "ebd8eb03503627471f39b036ff5dbb24070d21518d59aa8cbf962386257d21a4",
		"packer_freebsd_386":      "9ab4310d1d1048593278e4664591e7aa8f71d4bef9eda30e61d32323c14370cd",
		"packer_freebsd_amd64":    "be0c525eb5c7db8ef6412da9d0e2a967389de8df50b072395917be86fa95e8d8",
		"packer_freebsd_arm":      "bf9b885fde19be5cc4d70a68cc91ebdf3841d3e00c707f0e517a73ebd8a97297",
		"packer_linux_386":        "13c1a0cc1112807a6900d14c83f6d3ce79f9474eeab7a09031aba01cb68665f5",
		"packer_linux_amd64":      "2fd1149c5c6c7604ced64d7b56638af05f6b7ed3f6835182bc913ddaba1f16b8",
		"packer_linux_arm":        "7d5ee19adc7659720f03363c27e914945204eadb633ad5a3c37a3719f20e6eee",
		"packer_linux_arm64":      "1687f43bd120601f62e54b970b1cc06f83e95897357dc5c679b57ec9d2fb40a7",
		"packer_linux_ppc64le":    "0002e0cb37e60945c0438786e6e15613866b3b40ced0ec519c85ae1cae6b6a7a",
		"packer_netbsd_386":       "dc1ec730c6e37efdca36e2027a2414ab7ee6cf0380eff50f8466b4bf71a83ac2",
		"packer_netbsd_amd64":     "596cde300e18cd8270f671941e49d713933e5fa1105d43f73a87cb62b2789f38",
		"packer_netbsd_arm":       "1b4e5cd75aaa02c367c3f528b3e748cf4f5808fc40e7ba881efeefdea5ff0183",
		"packer_openbsd_386":      "027b0ecb539c98e4012b64544a858dc9c5dd5cf492b8f269e42c42f02ffb12fd",
		"packer_openbsd_amd64":    "8f8383b192d57af9d7dc2561ecd53c5d2bd448f4286ac07a48c34481c181212e",
		"packer_openbsd_arm":      "b57a602160c82e26fb601896606339ec59034a8591311326cfeca69d3b886993",
		"packer_solaris_amd64":    "26563bc9654df31cd0cc1665ced9602a650b99332b5114be1d9cb3d0eab23d86",
		"packer_windows_386":      "d3cb7f62b5834080c4437208e0e4a40028b8eba9967b432daa5d3df9927306ab",
		"packer_windows_amd64":    "5cf875e39b5d4ad552dd0e6f52a6e46c6d0b6b0ee1f8104824445892febe58c6",
	}
)
