/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by update-dependencies.sh. DO NOT EDIT.
package dependencies

var (
	TerraformVersion = "1.12.2"
	PackerVersion    = "1.15.3"

	ExpectedChecksums = map[string]string{
		"terraform_darwin_amd64":  "c65aa74bed1dbb1c48ba4bbab11f08e7f7eeb54a422146561490275340468f19",
		"terraform_darwin_arm64":  "1ca02f336ff4f993d6441806d38a0bcc0bbca0e3c877b84c9c2dc80cfcd0dc8b",
		"terraform_freebsd_386":   "1775139ffda321f730f91c0ce2bb2364c8eafe32c0d3950788086302d49d3005",
		"terraform_freebsd_amd64": "4a72a9770e971ad0fead17221b9488f4552d1a58a860b2a6b2c66ca15376b40e",
		"terraform_freebsd_arm":   "3ec3d8028b4e2977853cbf8f3119e2bbebb14c5bfa3542d90f0d32cac1b0df7d",
		"terraform_linux_386":     "73b380f262324985e911323ecc446066343ffe78add6570a122b7444b04b120b",
		"terraform_linux_amd64":   "1eaed12ca41fcfe094da3d76a7e9aa0639ad3409c43be0103ee9f5a1ff4b7437",
		"terraform_linux_arm":     "4d5d39d57755a45b7bb6c6ad7301ac3c301eba44b647e2d0ca79c117cb817259",
		"terraform_linux_arm64":   "f8a0347dc5e68e6d60a9fa2db361762e7943ed084a773f28a981d988ceb6fdc9",
		"terraform_openbsd_386":   "f92bbb5c7f2141d5b28a69d16770fd8b6afff5ff1b8ab0cfaab32e833b793b41",
		"terraform_openbsd_amd64": "7dc9bbfcf814386f3d680dc86d5f99eca78d2560863c0be219f9627c863ee903",
		"terraform_solaris_amd64": "2df462be97b21c61be3e82156f0d0f929808c2b9a9e2a1ce537bafcbbff61b80",
		"terraform_windows_386":   "5503656530278ff63741fd74609e847e181969ee96dd76fb722e11da40e19063",
		"terraform_windows_amd64": "0a1565ace9da37c2778868c2e97452d8fc25e40e530bafbbab97231e69b0a201",
		"packer_darwin_amd64":     "7718bee4a580d7c486263f10a28d00db7e8c600af08102ae118592ee30a50892",
		"packer_darwin_arm64":     "cca1601f2d187b084aa875183ae70e85521df0475fc0f61a7380e46df8980289",
		"packer_freebsd_386":      "4a3ae19821d7bd81855510a702a4d6262c10f76a837c32130b07832fab71dee7",
		"packer_freebsd_amd64":    "c07403daec93e0212075f8f517f69886f530f445f99fac315dd40a1824d564ea",
		"packer_freebsd_arm":      "b9af5f166a4a112c83ebb8c2eda76062e9c029acf3d7da927adbad1aad5dc7a9",
		"packer_linux_386":        "080c986c5e441197750ed1a6d5b398b558601218793b4bdcb16a040b9ecf0f05",
		"packer_linux_amd64":      "9ed712c9a8f223c7985d7d21c6b65744bf1c66b8aca333232b96f5ae3fd9c90d",
		"packer_linux_arm":        "ced0c4d91f2642affb8188459a167aafd7d62e660b59db9e7fa9bdcfdb895324",
		"packer_linux_arm64":      "ebf06f8f30a7e3bc69fa33ac8a5dfffefd70187df4541cccc6ef3f325b8ae4f1",
		"packer_linux_ppc64le":    "8efedaad3f21958bae164430d6cd8283059fe268798074bdd24b73127b8b7685",
		"packer_netbsd_386":       "afaf8faf32fde44fc6c45f2d450ebc7450b69ee50cb0a2639d2c241389a9c445",
		"packer_netbsd_amd64":     "aadaee8d1c3032ccc8fd073a55b2c6287e53f807168edf0b253d26284c61e9f3",
		"packer_netbsd_arm":       "5618745fb8307ebb6258e3922207fa30027d72290ad56c62d4dbe18b18b0d559",
		"packer_openbsd_386":      "4a553b05e44754c87399e9d3284fcd2fadb9db7be8ac415a7b995ea014b9cd1d",
		"packer_openbsd_amd64":    "a03c67d0391c447c6694396b1b61ef41ad89da6d9d3d2a59903db602a8ebcc96",
		"packer_openbsd_arm":      "63a704377eabff3329f1dd65801e4db820162ecac99414357334b39d8265b657",
		"packer_solaris_amd64":    "d01931e1f1a47df741156ad9bc9251ab0c5672511c6b753e12603ae300a18e83",
		"packer_windows_386":      "95422603cecbcb2afdb68e351d693f1d4c8de3a58de10674cb6864d9a041dd9d",
		"packer_windows_amd64":    "f0a256f13f8217070309f690e15ba76d53667f72da8efbcd33179d41c883ebdd",
	}
)
