# Copyright 2026 Google LLC
# ... (Keep your license header here)

- name: Gather instance information
  delegate_to: localhost
  when: deployment_name is defined and deployment_name | length > 0
  changed_when: false
  register: instances
  until: instances.rc == 0
  retries: 5
  delay: 10
  ansible.builtin.command: >-
    gcloud compute instances list
    --filter="labels.ghpc_deployment={{ deployment_name }}"
    --format='json(name,zone,id,status)'

- name: Print instance information
  when: instances.stdout is defined
  ansible.builtin.debug:
    var: instances.stdout

- name: Print Cloud Logging command
  ansible.builtin.debug:
    msg: "gcloud logging --project {{ project }} read 'logName=\"projects/{{ project }}/logs/google_metadata_script_runner\" AND resource.labels.instance_id=\"{{ item.id }}\"' --format=\"table(timestamp, jsonPayload.message)\" --freshness 24h | tac"
  when: instances.stdout is defined and (instances.stdout | from_json | length > 0)
  loop: "{{ instances.stdout | from_json | default([]) }}"