# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Set backward compatibility facts
  ansible.builtin.set_fact:
    _host_to_wait: "{{ host_to_wait | default(host_ip | default('')) }}"
    _is_private: "{{ is_private | default(false) | bool }}"

- name: Assert variables are defined
  ansible.builtin.assert:
    that:
    - _host_to_wait != ""

- name: Wait for firewall to allow port 22 connection
  ansible.builtin.wait_for:
    host: "{{ hostvars[_host_to_wait]['ansible_host'] | default(_host_to_wait) if _host_to_wait in hostvars else _host_to_wait }}"
    port: 22
    delay: 60
    timeout: 300
  delegate_to: localhost
  ignore_errors: true
  register: port_out
  when: not _is_private

- name: Check connection to remote host
  ansible.builtin.wait_for_connection:
    delay: 10
  delegate_to: "{{ _host_to_wait }}"
  ignore_unreachable: true
  register: connect_out

- name: Fail on bad connections
  ansible.builtin.fail:
    msg: "Failed to connect to remote host {{ _host_to_wait }}"
  when: (not _is_private and port_out is failed) or connect_out is failed
