# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=openfoam.yaml

steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://develop.openfoam.com/packaging/containers.git']
- name: 'bash'
  script: |
    cp -r containers/docker/* .
- name: 'gcr.io/$PROJECT_ID/apptainer'
  args:
  - 'build'
  - '--fakeroot'
  - 'openfoam2306.sif'
  - 'openfoam-run_rocky-template.def'
- name: 'gcr.io/$PROJECT_ID/apptainer'
  args:
  - 'push'
  - 'openfoam2306.sif'
  - 'oras://${_LOCATION}/$PROJECT_ID/${_REPOSITORY}/openfoam2306:${_VERSION}'
substitutions:
  _LOCATION: us-docker.pkg.dev
  _REPOSITORY: sifs
  _VERSION: latest
