# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Create VDI monitor script directory
  ansible.builtin.file:
    path: /usr/local/bin
    state: directory
    mode: '0755'

- name: Copy VDI monitor script
  ansible.builtin.template:
    src: vdi-monitor.sh.j2
    dest: /usr/local/bin/vdi-monitor.sh
    mode: '0755'
    owner: root
    group: root

- name: Copy VDI monitor systemd service
  ansible.builtin.template:
    src: vdi-monitor.service.j2
    dest: /etc/systemd/system/vdi-monitor.service
    mode: '0644'
    owner: root
    group: root

- name: Create VDI monitor log directory
  ansible.builtin.file:
    path: /var/log
    state: directory
    mode: '0755'

- name: Create VDI monitor log files
  ansible.builtin.file:
    path: "{{ item }}"
    state: touch
    mode: '0644'
    owner: root
    group: root
  loop:
    - /var/log/vdi-monitor.log
    - /var/log/ansible-vdi-reconfig.log

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable VDI monitor service
  ansible.builtin.systemd:
    name: vdi-monitor
    enabled: yes
    state: started

- name: Debug VDI monitor setup
  ansible.builtin.debug:
    msg: |
      VDI monitor service setup complete:
        - Service: vdi-monitor.service
        - Script: /usr/local/bin/vdi-monitor.sh
        - Logs: /var/log/vdi-monitor.log, /var/log/ansible-vdi-reconfig.log
        - Service enabled and started
  when: debug | default(false)
