# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
tags:
- m.custom-image
- m.cloud-storage-bucket
- m.pre-existing-network-storage
- m.filestore
- m.gpu-rdma-vpc
- m.schedmd-slurm-gcp-v6-controller
- m.schedmd-slurm-gcp-v6-login
- m.schedmd-slurm-gcp-v6-nodeset
- m.schedmd-slurm-gcp-v6-partition
- m.startup-script
- m.vpc
- slurm6

substitutions:
  _TEST_PREFIX: "" # Default to no prefix

timeout: 14400s  # 4hr
steps:

- id: ml-a3-ultragpu-onspot-slurm
  name: us-central1-docker.pkg.dev/$PROJECT_ID/hpc-toolkit-repo/test-runner
  entrypoint: /bin/bash
  env:
  - "ANSIBLE_HOST_KEY_CHECKING=false"
  - "ANSIBLE_CONFIG=/workspace/tools/cloud-build/ansible.cfg"
  - "PROJECT_ID=$PROJECT_ID"
  - "NUM_NODES=4"
  - "MACHINE_TYPE=a3-ultragpu-8g"
  - "INSTANCE_PREFIX=a3usp"
  - "BUILD_ID=$BUILD_ID"
  - "OPTIONS_GCS_PATH=gs://hpc-ctk1357/a3uoptions.txt"
  args:
  - -c
  - |
    set -e -u -o pipefail
    echo "Sourcing find_available_zone.sh to determine zone."
    source /workspace/tools/cloud-build/find_available_zone.sh
    if [ -z "$${ZONE:-}" ]; then
      echo "ERROR: ZONE not found" >&2
      exit 1
    fi
    set -x
    cd /workspace
    if [ "${_TEST_PREFIX}" == "daily-" ]; then
        gsutil cp gs://$${GCLUSTER_GCS_PATH}/latest/gcluster-bundle.zip .
        unzip -o gcluster-bundle.zip
        # Grant execution permissions to the binary
        chmod +x gcluster
    else
        make
    fi
    REGION="$${ZONE%-*}"
    BUILD_ID_SHORT="$${BUILD_ID:0:6}"
    BLUEPRINT="/workspace/examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml"
    sed -i -e '/deletion_protection:/{n;s/enabled: true/enabled: false/}' $${BLUEPRINT}
    sed -i -e '/reason:/d' $${BLUEPRINT}
    # Add this to your Cloud Build script before calling ansible-playbook
    sed -i "s/a3u-onspot-slurm-net/$${BUILD_ID_SHORT}-a3u-onspot-slurm-net/g" $${BLUEPRINT}

    ansible-playbook tools/cloud-build/daily-tests/ansible_playbooks/slurm-integration-test.yml \
      --user=sa_106486320838376751393 \
      --extra-vars="project=$${PROJECT_ID} build=$${BUILD_ID_SHORT}" \
      --extra-vars="region=$${REGION} zone=$${ZONE}" \
      --extra-vars="@tools/cloud-build/daily-tests/tests/ml-a3-ultragpu-onspot-slurm.yml"
  secretEnv: ['GCLUSTER_GCS_PATH']
availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/gcluster-develop-release-bucket/versions/latest
    env: 'GCLUSTER_GCS_PATH'
