/**
 * Copyright 2023 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

variable "ramble_path" {
  description = "Path to the Ramble installation"
  default     = null
  type        = string
}

variable "log_file" {
  description = "Log file to write output from Ramble execute steps into"
  default     = "/var/log/ramble-execute.log"
  type        = string
}

variable "spack_path" {
  description = "Path to the Spack installation"
  default     = null
  type        = string
}

variable "commands" {
  description = "String of commands to run within this module"
  default     = null
  type        = string
}

variable "ramble_runner" {
  description = <<-EOT
    Ansible based startup-script runner from a previous Ramble step
    Will automatically be prepended to the script generated by this module.
  EOT
  default     = null
  type = object({
    type        = string
    content     = string
    destination = string
  })
}
