/**
 * Copyright 2022 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

variable "project_id" {
  description = "Project in which Google Cloud Storage bucket will be created"
  type        = string
}

variable "deployment_name" {
  description = "HPC Toolkit deployment name. Cloud resource names will include this value."
  type        = string
}

variable "region" {
  description = "Default region for creating resources"
  type        = string
}

variable "zone" {
  description = "Default zone for creating resources"
  type        = string
}

variable "labels" {
  description = "Labels to add to the instances. List key, value pairs."
  type        = any
}

variable "network_self_link" {
  description = "The self link of the network to attach the VM."
  type        = string
  default     = "default"
}

variable "subnetwork_self_link" {
  description = "The self link of the subnetwork to attach the VM."
  type        = string
  default     = null
}

variable "pbs_server_rpm_url" {
  description = "Path to PBS Pro Server Host RPM file"
  type        = string
}

variable "pbs_client_rpm_url" {
  description = "Path to PBS Pro Client Host RPM file"
  type        = string
}

# tflint-ignore: terraform_unused_declarations
variable "pbs_execution_rpm_url" {
  description = "Path to PBS Pro Execution Host RPM file"
  type        = string
}

variable "pbs_exec" {
  description = "Root path in which to install PBS"
  type        = string
  default     = "/opt/pbs"
}

variable "pbs_data_service_user" {
  description = "PBS Data Service POSIX user"
  type        = string
  default     = "pbsdata"
}

variable "pbs_home" {
  description = "PBS working directory"
  type        = string
  default     = "/var/spool/pbs"
}

variable "pbs_license_server" {
  description = "IP address or DNS name of PBS license server"
  type        = string
}

variable "pbs_license_server_port" {
  description = "Netowrking port of PBS license server"
  type        = number
  default     = 6200
}

variable "network_storage" {
  description = "An array of network attached storage mounts to be configured."
  type = list(object({
    server_ip             = string,
    remote_mount          = string,
    local_mount           = string,
    fs_type               = string,
    mount_options         = string,
    client_install_runner = map(string)
    mount_runner          = map(string)
  }))
  default = []
}

variable "server_conf" {
  description = "A sequence of qmgr commands in format as generated by qmgr -c 'print server'"
  type        = string
  default     = "# empty qmgr configuration file"

  validation {
    condition     = var.server_conf != null && var.server_conf != ""
    error_message = "server_conf must be set to a non-empty string"
  }
}

variable "server_host_settings" {
  description = "Deploy 1 or more server hosts using vm-instance parameters (https://goo.gle/hpc-toolkit-vm-instance)"
  type        = any
  default     = {}
}

variable "client_host_settings" {
  description = "Deploy 0 or more client hosts using vm-instance parameters (https://goo.gle/hpc-toolkit-vm-instance)"
  type        = any
  default     = {}
}

variable "execution_host_settings" {
  description = "Deploy 0 or more execution hosts using vm-instance parameters (https://goo.gle/hpc-toolkit-vm-instance)"
  type        = any
  default     = {}
}
