# Copyright 2024 "Google LLC"
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Install and configure Docker
  hosts: all
  become: true
  vars:
    docker_data_root: ''
    docker_daemon_config: ''
    enable_docker_world_writable: false
    is_rocky_linux: "{{ ansible_distribution in ['Rocky', 'Rocky Linux'] }}"
  tasks:
  - name: Gather distribution facts
    ansible.builtin.setup:
      gather_subset: platform
  - name: Check if docker is installed
    ansible.builtin.stat:
      path: /usr/bin/docker
    register: docker_binary
  - name: Add Docker GPG key (Rocky)
    ansible.builtin.rpm_key:
      state: present
      key: https://download.docker.com/linux/rhel/gpg
    when:
    - is_rocky_linux
    - not docker_binary.stat.exists
    register: add_docker_key
    retries: 30
    delay: 10
    until: add_docker_key is succeeded
  - name: Add Docker repository for Rocky Linux
    ansible.builtin.command: >
      dnf config-manager --add-repo
      https://download.docker.com/linux/rhel/docker-ce.repo
    when:
    - is_rocky_linux
    - not docker_binary.stat.exists
    notify: Refresh dnf cache
  - name: Install Docker Engine and related packages on Rocky
    ansible.builtin.package:
      name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      state: present
      update_cache: yes
    when:
    - is_rocky_linux
    - not docker_binary.stat.exists
  - name: Ensure Docker SDK for Python is installed
    block:
    - name: Install python3-pip
      ansible.builtin.package:
        name: python3-pip
        state: present
    - name: Install Docker SDK for Python
      ansible.builtin.pip:
        name: docker
        executable: /usr/local/ghpc-venv/bin/pip3
    when: is_rocky_linux
  - name: Download Docker Installer (get.docker.com)
    ansible.builtin.get_url:
      url: https://get.docker.com
      dest: /tmp/get-docker.sh
      owner: root
      group: root
      mode: '0644'
    when:
    - not is_rocky_linux
    - not docker_binary.stat.exists
  - name: Install Docker
    ansible.builtin.command: sh /tmp/get-docker.sh
    register: docker_installed
    changed_when: docker_installed.rc != 0
    when:
    - not is_rocky_linux
    - not docker_binary.stat.exists
  - name: Create Docker daemon configuration
    ansible.builtin.copy:
      dest: /etc/docker/daemon.json
      mode: '0644'
      content: '{{ docker_daemon_config }}'
      validate: /usr/bin/dockerd --validate --config-file %s
    when: docker_daemon_config
    notify:
    - Restart Docker
  - name: Create Docker service override directory
    ansible.builtin.file:
      path: /etc/systemd/system/docker.service.d
      state: directory
      owner: root
      group: root
      mode: '0755'
  - name: Create Docker service override configuration
    ansible.builtin.copy:
      dest: /etc/systemd/system/docker.service.d/data-root.conf
      mode: '0644'
      content: |
        [Unit]
        {% if docker_data_root %}
        RequiresMountsFor={{ docker_data_root }}
        {% endif %}
        After=mount-localssd-raid.service
  - name: Create Docker socket override directory
    ansible.builtin.file:
      path: /etc/systemd/system/docker.socket.d
      state: directory
      owner: root
      group: root
      mode: '0755'
    when: enable_docker_world_writable
  - name: Create Docker socket override configuration
    ansible.builtin.copy:
      dest: /etc/systemd/system/docker.socket.d/world-writable.conf
      mode: '0644'
      content: |
        [Socket]
        SocketMode=0666
    when: enable_docker_world_writable
    notify:
    - Reload SystemD
    - Recreate Docker socket
  - name: Delete Docker socket override configuration
    ansible.builtin.file:
      path: /etc/systemd/system/docker.socket.d/world-writable.conf
      state: absent
    when: not enable_docker_world_writable
    notify:
    - Reload SystemD
    - Recreate Docker socket

  handlers:
  - name: Reload SystemD
    ansible.builtin.systemd:
      daemon_reload: true
  - name: Recreate Docker socket
    ansible.builtin.service:
      name: docker.socket
      state: restarted
  - name: Restart Docker
    ansible.builtin.service:
      name: docker.service
      state: restarted
  - name: Refresh dnf cache
    ansible.builtin.dnf:
      update_cache: yes

  post_tasks:
  - name: Start Docker
    ansible.builtin.service:
      name: docker.service
      state: started
      enabled: true
