# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Wait until all network interfaces are online for A3/A4 variants
  hosts: all
  become: true
  tasks:
  - name: Create SystemD service for A3 High networking
    when: ansible_os_family == "Debian"
    ansible.builtin.copy:
      dest: /etc/systemd/system/delay-a3-high.service
      owner: root
      group: root
      mode: "0644"
      content: |
        [Unit]
        Description=Delay A3 High boot until all network interfaces are routable
        After=network-online.target
        Wants=network-online.target
        Before=google-startup-scripts.service

        [Service]
        # Condition to only run on A3 High machines
        ExecCondition=/bin/bash -c '/usr/bin/curl -s -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/machine-type | grep -q "/a3-highgpu-8g$"'
        ExecStart=/usr/lib/systemd/systemd-networkd-wait-online -i enp0s12 -i enp6s0 -i enp12s0 -i enp134s0 -i enp140s0 -o routable --timeout=180
        ExecStartPost=/bin/sleep 30

        [Install]
        WantedBy=multi-user.target
    notify:
    - Reload SystemD

  - name: Create SystemD service for A3 Mega networking
    when: ansible_os_family == "Debian"
    ansible.builtin.copy:
      dest: /etc/systemd/system/delay-a3-mega.service
      owner: root
      group: root
      mode: "0644"
      content: |
        [Unit]
        Description=Delay A3 Mega boot until all network interfaces are routable
        After=network-online.target
        Wants=network-online.target
        Before=google-startup-scripts.service

        [Service]
        # Condition to only run on A3 Mega machines
        ExecCondition=/bin/bash -c '/usr/bin/curl -s -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/machine-type | grep -q "/a3-megagpu-8g$"'
        ExecStart=/usr/lib/systemd/systemd-networkd-wait-online -i enp0s12 -i enp6s0f0 -i enp7s0f0 -i enp13s0f0 -i enp14s0f0 -i enp134s0f0 -i enp135s0f0 -i enp141s0f0 -i enp142s0f0 -o routable --timeout=180
        ExecStartPost=/bin/sleep 30

        [Install]
        WantedBy=multi-user.target
    notify:
    - Reload SystemD

  - name: Create SystemD service for A3 Ultra networking
    when: ansible_os_family == "Debian"
    ansible.builtin.copy:
      dest: /etc/systemd/system/delay-a3-ultra.service
      owner: root
      group: root
      mode: "0644"
      content: |
        [Unit]
        Description=Delay A3 Ultra boot until all network interfaces are routable
        After=network-online.target
        Wants=network-online.target
        Before=google-startup-scripts.service

        [Service]
        # Condition to only run on A3 Ultra machines
        ExecCondition=/bin/bash -c '/usr/bin/curl -s -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/machine-type | grep -q "/a3-ultragpu-8g$"'
        ExecStart=/usr/lib/systemd/systemd-networkd-wait-online -i enp0s19 -i enp192s20 -i gpu0rdma0 -i gpu1rdma0 - gpu2rdma0 -i gpu3rdma0 -i gpu4rdma0 -i gpu5rdma0 -i gpu6rdma0 -i gpu7rdma0 -o routable --timeout=180
        ExecStartPost=/bin/sleep 30

        [Install]
        WantedBy=multi-user.target
    notify:
    - Reload SystemD

  - name: Create SystemD service for A4 High networking
    when: ansible_os_family == "Debian"
    ansible.builtin.copy:
      dest: /etc/systemd/system/delay-a4-high.service
      owner: root
      group: root
      mode: "0644"
      content: |
        [Unit]
        Description=Delay A4 High boot until all network interfaces are routable
        After=network-online.target
        Wants=network-online.target
        Before=google-startup-scripts.service

        [Service]
        # Condition to only run on A4 High machines
        ExecCondition=/bin/bash -c '/usr/bin/curl -s -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/machine-type | grep -q "/a4-highgpu-8g$"'
        ExecStart=/usr/lib/systemd/systemd-networkd-wait-online -i enp0s19 -i enp192s20 -i gpu0rdma0 -i gpu1rdma0 - gpu2rdma0 -i gpu3rdma0 -i gpu4rdma0 -i gpu5rdma0 -i gpu6rdma0 -i gpu7rdma0 -o routable --timeout=180
        ExecStartPost=/bin/sleep 30
        # To debug interface names on an A4 instance, run: ip link show

        [Install]
        WantedBy=multi-user.target
    notify:
    - Reload SystemD

  - name: Enable A3/A4 delay services
    when: ansible_os_family == "Debian"
    ansible.builtin.systemd_service:
      name: "{{ item }}"
      enabled: true
    loop:
    - delay-a3-high.service
    - delay-a3-mega.service
    - delay-a3-ultra.service
    - delay-a4-high.service

  handlers:
  - name: Reload SystemD
    ansible.builtin.systemd:
      daemon_reload: true
