# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=lolcow.yaml

steps:
- name: 'gcr.io/$PROJECT_ID/apptainer'
  args:
  - 'build'
  - '--fakeroot'
  - 'lolcow.sif'
  - 'lolcow.def'
- name: 'gcr.io/$PROJECT_ID/apptainer'
  args:
  - 'push'
  - 'lolcow.sif'
  - 'oras://${_LOCATION}/$PROJECT_ID/${_REPOSITORY}/lolcow:${_VERSION}'
substitutions:
  _LOCATION: us-docker.pkg.dev
  _REPOSITORY: sifs
  _VERSION: latest
