# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

vars:
  region: us-central1
  zone: us-central1-a

  slurm_gcp_version: 6.10.4

  # to supply
  family:
  project_id:
  deployment_name:
  packer_metadata:
    user-data: |
      #cloud-config
      write_files:
      - path: /etc/apt/apt.conf.d/20auto-upgrades
        permissions: '0644'
        owner: root
        content: |
          APT::Periodic::Update-Package-Lists "0";
          APT::Periodic::Unattended-Upgrade "0";

  runner_write_gcluster_build_info:
    type: data
    destination: /etc/gcluster-build-info
    source: $(ghpc_stage("../gcluster-build-info"))

  runner_install_slurm:
    type: shell
    destination: install_slurm.sh
    content: |
      #!/bin/bash
      set -e -o pipefail
      ansible-pull \
          -U https://github.com/GoogleCloudPlatform/slurm-gcp -C $(vars.slurm_gcp_version) \
          -i localhost, --limit localhost --connection=local \
          -e @/var/tmp/slurm_vars.json \
          ansible/playbook.yml

  # this duplicates the ulimits configuration of the HPC VM Image
  runner_setup_hpc_vm_image_ulimits:
    type: data
    destination: /etc/security/limits.d/99-unlimited.conf
    content: |
      * - memlock unlimited
      * - nproc unlimited
      * - stack unlimited
      * - nofile 1048576
      * - cpu unlimited
      * - rtprio unlimited

  runner_install_cluster_health_scanner:
    type: ansible-local
    destination: install_cluster_health_scanner.yml
    content: |
      ---
      - name: Install Cluster Health Scanner
        hosts: localhost
        vars:
          git_version: d9268a0a331eb5c4f7214b33fc0814f60afce846
        tasks:
        - name: Clone cluster-health-scanner
          ansible.builtin.git:
            repo: https://github.com/GoogleCloudPlatform/cluster-health-scanner.git
            dest: /opt/cluster-health-scanner
            version: "{{ git_version }}"
            force: true
        - name: Change permissions of cluster-validation.sh
          ansible.builtin.file:
            path: /opt/cluster-health-scanner/deploy/slurm/cluster-validation.sh
            mode: '0755'
