# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# Check if this role should run
- name: Set current role for lock manager check
  ansible.builtin.set_fact:
    current_role: "vdi_tool"

- name: Check if vdi_tool role should run
  ansible.builtin.import_role:
    name: lock_manager
    tasks_from: check_lock
  register: lock_check_result

- name: Set role_should_run from lock check result
  ansible.builtin.set_fact:
    role_should_run: "{{ lock_check_result.ansible_facts.role_should_run | default(true) }}"

- name: Check if user secrets changed
  ansible.builtin.set_fact:
    user_secrets_changed: "{{ lock_check_result.ansible_facts.user_secrets_changed | default(false) }}"

- name: Override role_should_run if user secrets changed
  ansible.builtin.set_fact:
    role_should_run: true
  when: user_secrets_changed

- name: Debug vdi_tool role execution reason
  ansible.builtin.debug:
    msg: |
      VDI tool role execution:
        - role_should_run: {{ role_should_run }}
        - user_secrets_changed: {{ user_secrets_changed }}
        - execution_reason: {{ 'User configuration changed' if user_secrets_changed else 'Normal role execution' }}
  when: role_should_run

# Skip all tasks if role should not run
- name: Skip vdi_tool tasks if role should not run
  ansible.builtin.debug:
    msg: "Skipping vdi_tool role - already completed or not needed"
  when: not role_should_run

- name: "Install Guacamole"
  include_tasks: guacamole.yaml
  when: 
    - vdi_tool | lower == 'guacamole'
    - role_should_run

- name: "Install NoMachine"
  include_tasks: nomachine.yaml
  when: 
    - vdi_tool | lower == 'nomachine'
    - role_should_run

- name: "Install Workspot"
  include_tasks: workspot.yaml
  when: 
    - vdi_tool | lower == 'workspot'
    - role_should_run

# Mark role as completed
- name: Set current role for lock manager completion
  ansible.builtin.set_fact:
    current_role: "vdi_tool"
    role_completed: true
  when: role_should_run

- name: Mark vdi_tool role as completed
  ansible.builtin.import_role:
    name: lock_manager
    tasks_from: create_lock
  when: role_should_run
