# Copyright 2024 "Google LLC"
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

terraform_backend_defaults:
  type: gcs
  configuration:
    # The GCS bucket used for storing terraform state
    bucket:

vars:
  # Your GCP Project ID
  project_id:

  # This should be unique across all of your Cluster
  # Toolkit Deployments.
  deployment_name: a3u-gke-gcs

  # The GCP Region used for this deployment.
  region:

  # The GCP Zone used for this deployment.
  zone:

  # The number of nodes to be created
  static_node_count:

  # Cidr block containing the IP of the machine calling terraform.
  # To allow all (IAM restrictions still enforced), use 0.0.0.0/0
  # To allow only your IP address, use <YOUR-IP-ADDRESS>/32
  authorized_cidr:

  # The name of the compute engine reservation of A3-Ultra nodes in the form of
  # <project>/<reservation-name>/reservationBlocks/<reservation-block-name>
  extended_reservation:

  # The name of the GCS bucket used for training data
  training_bucket_name:

  # The name of the GCS bucket used for checkpoint/restart data.
  checkpoint_bucket_name:
