#!/bin/bash
# Copyright 2026 "Google LLC"
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# bash tools/update-dependencies.sh

set -euo pipefail

TERRAFORM_VERSION="1.12.2"
PACKER_VERSION="1.15.0"
OUTPUT_FILE="pkg/dependencies/checksums_generated.go"

mkdir -p "$(dirname "$OUTPUT_FILE")"

# Create or overwrite the generated file
cat <<EOF >"$OUTPUT_FILE"
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by $(basename "$0"). DO NOT EDIT.
package dependencies

var (
	TerraformVersion = "${TERRAFORM_VERSION}"
	PackerVersion    = "${PACKER_VERSION}"

	ExpectedChecksums = map[string]string{
EOF

process_dependency() {
	local name="$1"
	local version="$2"
	local output_file="$3"

	echo "Fetching ${name} ${version} checksums..."
	curl -sSL "https://releases.hashicorp.com/${name}/${version}/${name}_${version}_SHA256SUMS" | while read -r sha256 filename; do
		if [[ $filename =~ ${name}_${version}_([a-zA-Z0-9_]+)\.zip$ ]]; then
			local os_arch="${BASH_REMATCH[1]}"
			echo "		\"${name}_${os_arch}\": \"${sha256}\"," >>"${output_file}"
		fi
	done
}

process_dependency "terraform" "${TERRAFORM_VERSION}" "${OUTPUT_FILE}"
process_dependency "packer" "${PACKER_VERSION}" "${OUTPUT_FILE}"

cat <<EOF >>"$OUTPUT_FILE"
	}
)
EOF

go fmt $OUTPUT_FILE

echo "Done generating ${OUTPUT_FILE}"
