# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Creates SSH Keys to communicate between hosts
  hosts: localhost
  vars:
    pub_key_path: ~/.ssh
    pub_key_file: "{{pub_key_path}}/id_rsa"
    auth_key_file: "{{pub_key_path}}/authorized_keys"
  tasks:
  - name: "Create {{pub_key_path}} folder"
    file:
      path: "{{pub_key_path}}"
      state: directory
      mode: 0700
  - name: Create keys
    openssh_keypair:
      path: "{{pub_key_file}}"
  - name: Copy public key to authorized keys
    copy:
      src: "{{pub_key_file}}.pub"
      dest: "{{auth_key_file}}"
      mode: 0644

- name: install_deps
  hosts: localhost
  tasks:
  - name: Install git and epel-release
    package:
      name:
      - git
      - epel-release
      state: latest

- name: setup_omnia
  hosts: localhost
  tasks:
  - name: Unmask and restart firewalld
    become: yes
    command: systemctl unmask firewalld && systemctl restart firewalld
  - name: Git checkout
    git:
      repo: 'https://github.com/dellhpc/omnia.git'
      dest: ../omnia
      version: release
      update: false
  - name: Copy file with owner and permissions
    copy:
      src: ../data/inventory
      dest: ../omnia/inventory
      mode: 0644
  - name: Update omnia.yml setting become to yes
    replace:
      path: ../omnia/omnia.yml
      regexp: '- name(.*)'
      replace: '- name\1\n  become: yes'

- name: run_omnia # Look into import_playbook here
  hosts: localhost
  tasks:
  - name: Run omnia
    shell: |
      ansible-playbook omnia.yml -i inventory \
        --e "ansible_python_interpreter=/usr/bin/python2" \
        --skip-tags "kubernetes"
    args:
      chdir: ../omnia
    environment:
      ANSIBLE_HOST_KEY_CHECKING: False


