# Copyright 2026 "Google LLC"
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: GitHub Actions Scan - Develop

on:
  pull_request_target:
    branches:
    - develop

permissions:
  id-token: write
  contents: read

jobs:
  github-actions-scan:
    uses: google-gh-automation/workflows/.github/workflows/github_actions_scan.yml@22b63c643fbe7b395b00cc3952ab552decc586c7 #actions-20260622-02
